# MySQL.  Versions 5.0+ are recommended.
#
# Install the MYSQL driver
#   gem install mysql2
#
# Ensure the MySQL gem is defined in your Gemfile
#   gem 'mysql2'
#
# And be sure to use new-style password hashing:
#   http://dev.mysql.com/doc/refman/5.0/en/old-client.html
#

development:
  adapter: mysql2
  encoding: utf8
  pool: 5
  database: singleapp_development
  username: root
  password: nimbu
  socket: /var/run/mysqld/mysqld.sock


production:
  adapter: postgresql
  database: singleapp_example
  pool: 5
  timeout: 5000






